var i = 7
global.esperienza_livello[0] = 0
global.esperienza_livello[(1 << 0)] = 0
global.esperienza_livello[(2 << 0)] = 1200
global.esperienza_livello[(3 << 0)] = 4000
global.esperienza_livello[(4 << 0)] = 10000
global.esperienza_livello[(5 << 0)] = 20000
global.esperienza_livello[(6 << 0)] = 40000
global.esperienza_livello[(8 << 0)] = 65000
global.esperienza_livello[(7 << 0)] = 200000
global.esperienza_nome_livello[(1 << 0)] = "Rookie"
global.esperienza_nome_livello[(2 << 0)] = "Intermediate"
global.esperienza_nome_livello[(3 << 0)] = "Skilled"
global.esperienza_nome_livello[(4 << 0)] = "Expert"
global.esperienza_nome_livello[(5 << 0)] = "Veteran"
global.esperienza_nome_livello[(6 << 0)] = "Master"
global.esperienza_nome_livello[(7 << 0)] = "Legend"
global.esperienza_nome_livello[(8 << 0)] = "MAX"
