open = false
id_door = 0
var a = (0 << 0)
global.door_id[a] = a
global.door_sprite_close[a] = 1805
global.door_sprite_open[a] = 1806
global.door_key_id[a] = "key_stazione_polizia_villaggio"
global.door_sound_close[a] = 0
global.door_sound_open[a] = 0
a = (1 << 0)
global.door_id[a] = a
global.door_sprite_close[a] = 1809
global.door_sprite_open[a] = 1810
global.door_key_id[a] = "key_laboratory_makeshift_camp"
global.door_sound_close[a] = 0
global.door_sound_open[a] = 0
a = (3 << 0)
global.door_id[a] = a
global.door_sprite_close[a] = 1809
global.door_sprite_open[a] = 1810
global.door_key_id[a] = "key_laboratory_doc_room"
global.door_sound_close[a] = 0
global.door_sound_open[a] = 0
a = (2 << 0)
global.door_id[a] = a
global.door_sprite_close[a] = 1809
global.door_sprite_open[a] = 1810
global.door_key_id[a] = "key_laboratory_supply_room"
global.door_sound_close[a] = 0
global.door_sound_open[a] = 0
a = (4 << 0)
global.door_id[a] = a
global.door_sprite_close[a] = 1809
global.door_sprite_open[a] = 1810
global.door_key_id[a] = "key_oil_blue"
global.door_sound_close[a] = 0
global.door_sound_open[a] = 0
a = (5 << 0)
global.door_id[a] = a
global.door_sprite_close[a] = 1809
global.door_sprite_open[a] = 1810
global.door_key_id[a] = "key_oil_green"
global.door_sound_close[a] = 0
global.door_sound_open[a] = 0
a = (6 << 0)
global.door_id[a] = a
global.door_sprite_close[a] = 1809
global.door_sprite_open[a] = 1810
global.door_key_id[a] = "key_oil_violet"
global.door_sound_close[a] = 0
global.door_sound_open[a] = 0
a = (7 << 0)
global.door_id[a] = a
global.door_sprite_close[a] = 1805
global.door_sprite_open[a] = 1806
global.door_key_id[a] = "key_sewer"
global.door_sound_close[a] = 0
global.door_sound_open[a] = 0
a = (8 << 0)
global.door_id[a] = a
global.door_sprite_close[a] = 1805
global.door_sprite_open[a] = 1806
global.door_key_id[a] = "key_gears"
global.door_sound_close[a] = 0
global.door_sound_open[a] = 0
a = (9 << 0)
global.door_id[a] = a
global.door_sprite_close[a] = 1809
global.door_sprite_open[a] = 1810
global.door_key_id[a] = "key_mall_guns_store"
global.door_sound_close[a] = 0
global.door_sound_open[a] = 0
a = (10 << 0)
global.door_id[a] = a
global.door_sprite_close[a] = 1805
global.door_sprite_open[a] = 1806
global.door_key_id[a] = "key_mall_svaroski"
global.door_sound_close[a] = 0
global.door_sound_open[a] = 0
a = (11 << 0)
global.door_id[a] = a
global.door_sprite_close[a] = 1805
global.door_sprite_open[a] = 1806
global.door_key_id[a] = "key_mall_tech_store"
global.door_sound_close[a] = 0
global.door_sound_open[a] = 0
a = (12 << 0)
global.door_id[a] = a
global.door_sprite_close[a] = 1805
global.door_sprite_open[a] = 1806
global.door_key_id[a] = "key_mall_office"
global.door_sound_close[a] = 0
global.door_sound_open[a] = 0
a = (14 << 0)
global.door_id[a] = a
global.door_sprite_close[a] = 1805
global.door_sprite_open[a] = 1806
global.door_key_id[a] = "key_mall_extract"
global.door_sound_close[a] = 0
global.door_sound_open[a] = 0
a = (13 << 0)
global.door_id[a] = a
global.door_sprite_close[a] = 1809
global.door_sprite_open[a] = 1810
global.door_key_id[a] = "key_mall_turbine"
global.door_sound_close[a] = 0
global.door_sound_open[a] = 0
