audio_listener_position(x, y, 0)
audio_emitter_position(emitter_shoot, x, y, 0)
audio_emitter_position(emitter_walk, x, y, 0)
depth = (-bbox_bottom)
weapon_holder.weapon_holder.func_end_step()
if (arms_holder != undefined)
    arms_holder.arms_holder.func_step()
