function gamedata_clear() //gml_Script_gamedata_clear
{
    global.npc_data = {}
    global.npc_preset = {}
    global.item_data = {}
    global.caliber_data = {}
    global.mod_pos_data = {}
    global.mod_type_data = {}
    global.weapon_type_data = {}
    global.weapon_glance_stat = {}
    global.loadout_data = {}
    global.category_data = {}
    global.trader_data = {}
    global.trader_pages_data = {}
    global.chest_data = {}
    global.chest_sound_data = {}
    global.speaker_data = {}
    global.stat_data = {}
    global.gamepad_data = {}
    global.language_data = {}
    global.npc_data_array = []
    global.npc_preset_array = []
    global.item_data_array = []
    global.caliber_data_array = []
    global.mod_pos_data_array = []
    global.mod_type_data_array = []
    global.weapon_type_data_array = []
    global.weapon_glance_stat_array = []
    global.loadout_data_array = []
    global.category_data_array = []
    global.trader_data_array = []
    global.trader_pages_data_array = []
    global.chest_data_array = []
    global.chest_sound_data_array = []
    global.speaker_data_array = []
    global.stat_data_array = []
    global.gamepad_data_array = []
    global.language_data_array = []
    global.item_all_weapon_array = []
    global.item_possible_mod_data = {}
    global.item_debug_spawner_data = {}
    global.caliber_ammo_data = {}
}

