radiation_amount_shader = shader_get_uniform(shd_gray, "gray_amount")
global.night_vision = false
radiation_amount = 0
shader_radiation_time = shader_get_uniform(shd_radiation, "grain_time")
shader_radiation_intensity = shader_get_uniform(shd_radiation, "grain_intensity")
surface_inventory = -4
global.surface_nvg = -4
contrast_amount = -0.25
brightness_amount = 0.17
gamma_amount = 1
grain_amount = 0.2
