depth = -9999
timer_audio = 0
timer_audio_max = 60
a = 0
a_plus = 0.015
exp_agg = 0
exp_agg_start = 0
exp_agg_finish = 0
exp_agg_counter = 0
exp_agg_counter_max = 180
exp_bar_start = false
alarm[0] = 180
alarm[3] = 1
exp_numero_start = false
alarm[1] = 120
can_go_hub = false
survived = true
factor_survived = 1
exp_agg_start = global.esperienza
global.esperienza_survive += (global.esperienza_loot + global.esperienza_kill)
global.esperienza_survive *= gml_Script_difficulty_get("pro_reputation_multiplier")
exp_agg_finish = 0
exp_numero_max = 0
exp_numero = 0
button_next_hover = false
button_next_w = 96
button_next_h = 24
button_next_x = 240
button_next_y = 225
button_show_diff_x = 240
button_show_diff_y = 250
button_show_diff_hover = false
button_show_diff_w = 112
button_show_diff_h = 16
skip_all = false
skip_done = false
var _value_preraid = db_read_ext("pre_raid", "inventory_value", "pre_raid", 0)
var _value_raid = inventory_get_total_value()
value_made = round(gml_Script_difficulty_get("trade_sell_mult") * (_value_raid - _value_preraid))
