skills_reset()
function skills_reset() //gml_Script_skills_reset
{
    var a = (0 << 0)
    global.sk_lvl[a] = 0
    global.sk_last_level[a] = -1
    a = (1 << 0)
    global.sk_lvl[a] = -1
    global.sk_last_level[a] = -1
    a = (2 << 0)
    global.sk_lvl[a] = -1
    global.sk_last_level[a] = -1
    a = (3 << 0)
    global.sk_lvl[a] = -1
    global.sk_last_level[a] = -1
    a = (4 << 0)
    global.sk_lvl[a] = 0
    global.sk_last_level[a] = -1
    a = (5 << 0)
    global.sk_lvl[a] = -1
    global.sk_last_level[a] = -1
    a = (6 << 0)
    global.sk_lvl[a] = -1
    global.sk_last_level[a] = -1
    a = (7 << 0)
    global.sk_lvl[a] = -1
    global.sk_last_level[a] = -1
    a = (8 << 0)
    global.sk_lvl[a] = 0
    global.sk_last_level[a] = -1
    a = (9 << 0)
    global.sk_lvl[a] = -1
    global.sk_last_level[a] = -1
    a = (10 << 0)
    global.sk_lvl[a] = -1
    global.sk_last_level[a] = -1
    a = (11 << 0)
    global.sk_lvl[a] = -1
    global.sk_last_level[a] = -1
    a = (12 << 0)
    global.sk_lvl[a] = 0
    global.sk_last_level[a] = -1
    a = (13 << 0)
    global.sk_lvl[a] = -1
    global.sk_last_level[a] = -1
    a = (14 << 0)
    global.sk_lvl[a] = -1
    global.sk_last_level[a] = -1
    a = (15 << 0)
    global.sk_lvl[a] = -1
    global.sk_last_level[a] = -1
    a = (16 << 0)
    global.sk_lvl[a] = 0
    global.sk_last_level[a] = -1
    a = (17 << 0)
    global.sk_lvl[a] = -1
    global.sk_last_level[a] = -1
    a = (18 << 0)
    global.sk_lvl[a] = -1
    global.sk_last_level[a] = -1
    a = (22 << 0)
    global.sk_lvl[a] = 0
    global.sk_last_level[a] = -1
    a = (23 << 0)
    global.sk_lvl[a] = -1
    global.sk_last_level[a] = -1
    a = (24 << 0)
    global.sk_lvl[a] = -1
    global.sk_last_level[a] = -1
    a = (19 << 0)
    global.sk_lvl[a] = 0
    global.sk_last_level[a] = -1
    a = (20 << 0)
    global.sk_lvl[a] = -1
    global.sk_last_level[a] = -1
    a = (21 << 0)
    global.sk_lvl[a] = -1
    global.sk_last_level[a] = -1
}

