function lista_azioni() //gml_Script_lista_azioni
{
    var a = (0 << 0)
    global.az_section[a] = "az_" + string(a)
    global.az_key[a] = "az_" + string(a)
    global.az_done[a] = false
    a = (1 << 0)
    global.az_section[a] = "az_" + string(a)
    global.az_key[a] = "az_" + string(a)
    global.az_done[a] = false
    a = (2 << 0)
    global.az_section[a] = "az_" + string(a)
    global.az_key[a] = "az_" + string(a)
    global.az_done[a] = false
    a = (3 << 0)
    global.az_section[a] = "az_" + string(a)
    global.az_key[a] = "az_" + string(a)
    global.az_done[a] = false
    a = (4 << 0)
    global.az_section[a] = "az_" + string(a)
    global.az_key[a] = "az_" + string(a)
    global.az_done[a] = false
    a = (5 << 0)
    global.az_section[a] = "az_" + string(a)
    global.az_key[a] = "az_" + string(a)
    global.az_done[a] = false
    a = (6 << 0)
    global.az_section[a] = "az_" + string(a)
    global.az_key[a] = "az_" + string(a)
    global.az_done[a] = false
    a = (7 << 0)
    global.az_section[a] = "az_" + string(a)
    global.az_key[a] = "az_" + string(a)
    global.az_done[a] = false
    a = (8 << 0)
    global.az_section[a] = "az_" + string(a)
    global.az_key[a] = "az_" + string(a)
    global.az_done[a] = false
    a = (9 << 0)
    global.az_section[a] = "az_" + string(a)
    global.az_key[a] = "az_" + string(a)
    global.az_done[a] = false
    a = (10 << 0)
    global.az_section[a] = "az_" + string(a)
    global.az_key[a] = "az_" + string(a)
    global.az_done[a] = false
    a = (11 << 0)
    global.az_section[a] = "az_" + string(a)
    global.az_key[a] = "az_" + string(a)
    global.az_done[a] = false
    a = (12 << 0)
    global.az_section[a] = "az_" + string(a)
    global.az_key[a] = "az_" + string(a)
    global.az_done[a] = false
    a = (13 << 0)
    global.az_section[a] = "az_" + string(a)
    global.az_key[a] = "az_" + string(a)
    global.az_done[a] = false
    a = (14 << 0)
    global.az_section[a] = "az_" + string(a)
    global.az_key[a] = "az_" + string(a)
    global.az_done[a] = false
    a = (15 << 0)
    global.az_section[a] = "az_" + string(a)
    global.az_key[a] = "az_" + string(a)
    global.az_done[a] = false
    a = (16 << 0)
    global.az_section[a] = "az_" + string(a)
    global.az_key[a] = "az_" + string(a)
    global.az_done[a] = false
    scr_load_unique_action()
}

