function fun_ga_diff_setting(argument0) //gml_Script_fun_ga_diff_setting
{
    if (argument0 == undefined)
        argument0 = 1
    var _pre = "Diff:lvl_" + string(argument0) + ":"
    ga_addDesignEvent((_pre + "trade_sell_mult:" + string(gml_Script_difficulty_get("trade_sell_mult"))), 1)
    ga_addDesignEvent((_pre + "trade_item_amount:" + string(gml_Script_difficulty_get("trade_item_amount"))), 1)
    ga_addDesignEvent((_pre + "trade_trader_money:" + string(gml_Script_difficulty_get("trade_trader_money"))), 1)
    ga_addDesignEvent((_pre + "trade_price_weapon:" + string(gml_Script_difficulty_get("trade_price_weapon"))), 1)
    ga_addDesignEvent((_pre + "trade_price_armor:" + string(gml_Script_difficulty_get("trade_price_armor"))), 1)
    ga_addDesignEvent((_pre + "trade_price_backpack:" + string(gml_Script_difficulty_get("trade_price_backpack"))), 1)
    ga_addDesignEvent((_pre + "trade_price_ammo:" + string(gml_Script_difficulty_get("trade_price_ammo"))), 1)
    ga_addDesignEvent((_pre + "trade_price_medication:" + string(gml_Script_difficulty_get("trade_price_medication"))), 1)
    ga_addDesignEvent((_pre + "loot_item_amount:" + string(gml_Script_difficulty_get("loot_item_amount"))), 1)
    ga_addDesignEvent((_pre + "loot_amount_single_item:" + string(gml_Script_difficulty_get("loot_amount_single_item"))), 1)
    ga_addDesignEvent((_pre + "loot_weapon_dur_min:" + string(gml_Script_difficulty_get("loot_weapon_dur_min"))), 1)
    ga_addDesignEvent((_pre + "loot_weapon_dur_max:" + string(gml_Script_difficulty_get("loot_weapon_dur_max"))), 1)
    ga_addDesignEvent((_pre + "loot_npc_drop_armor:" + string(gml_Script_difficulty_get("loot_npc_drop_armor"))), 1)
    ga_addDesignEvent((_pre + "loot_npc_drop_ammo:" + string(gml_Script_difficulty_get("loot_npc_drop_ammo"))), 1)
    ga_addDesignEvent((_pre + "pro_player_health:" + string(gml_Script_difficulty_get("pro_player_health"))), 1)
    ga_addDesignEvent((_pre + "pro_min_carry_weight:" + string(gml_Script_difficulty_get("pro_min_carry_weight"))), 1)
    ga_addDesignEvent((_pre + "pro_hunger_thirst_rate:" + string(gml_Script_difficulty_get("pro_hunger_thirst_rate"))), 1)
    ga_addDesignEvent((_pre + "pro_reputation_multiplier:" + string(gml_Script_difficulty_get("pro_reputation_multiplier"))), 1)
    ga_addDesignEvent((_pre + "pro_exp_multiplier:" + string(gml_Script_difficulty_get("pro_exp_multiplier"))), 1)
    ga_addDesignEvent((_pre + "pro_quest_rep:" + string(gml_Script_difficulty_get("pro_quest_rep"))), 1)
    ga_addDesignEvent((_pre + "pro_quest_money:" + string(gml_Script_difficulty_get("pro_quest_money"))), 1)
    ga_addDesignEvent((_pre + "pro_quest_item:" + string(gml_Script_difficulty_get("pro_quest_item"))), 1)
    ga_addDesignEvent((_pre + "pro_service_price:" + string(gml_Script_difficulty_get("pro_service_price"))), 1)
    ga_addDesignEvent((_pre + "enemy_human_hp:" + string(gml_Script_difficulty_get("enemy_human_hp"))), 1)
    ga_addDesignEvent((_pre + "enemy_human_damage:" + string(gml_Script_difficulty_get("enemy_human_damage"))), 1)
    ga_addDesignEvent((_pre + "enemy_mutant_hp:" + string(gml_Script_difficulty_get("enemy_mutant_hp"))), 1)
    ga_addDesignEvent((_pre + "enemy_mutant_damage:" + string(gml_Script_difficulty_get("enemy_mutant_damage"))), 1)
    ga_addDesignEvent((_pre + "hardcore_lose_equipment:" + string(gml_Script_difficulty_get("hardcore_lose_equipment"))), 1)
    ga_addDesignEvent((_pre + "hardcore_lose_ammo:" + string(gml_Script_difficulty_get("hardcore_lose_ammo"))), 1)
    ga_addDesignEvent((_pre + "hardcore_lose_medication:" + string(gml_Script_difficulty_get("hardcore_lose_medication"))), 1)
    ga_addDesignEvent((_pre + "hardcore_lose_consumable:" + string(gml_Script_difficulty_get("hardcore_lose_consumable"))), 1)
    ga_addDesignEvent((_pre + "hardcore_lose_keys:" + string(gml_Script_difficulty_get("hardcore_lose_keys"))), 1)
    ga_addDesignEvent((_pre + "hardcore_lose_other:" + string(gml_Script_difficulty_get("hardcore_lose_other"))), 1)
    ga_addDesignEvent((_pre + "hardcore_perma_death:" + string(gml_Script_difficulty_get("hardcore_perma_death"))), 1)
}

